"""
FastAPI — User Behavior Analysis endpoint.

Memory strategy
---------------
session_metrics.parquet is ~1.3 GB (one row per raw session).  Reading it in
full would exceed any reasonable laptop memory budget.  Instead we use two
tactics:

1. session_stats  — DuckDB reservoir sample of 200 000 rows.  This gives
   statistically accurate averages without touching more than ~20 MB of data.

2. sessions_distribution — read from user_segments (1 row/user, ~56 MB),
   which already has total_sessions pre-aggregated per user.

Everything else (hourly heatmap, segment distribution) reads small tables.
"""

import os
from fastapi import APIRouter, Query
from typing import Optional
from db import query, table, get_table_path

router = APIRouter(prefix="/api/behavior", tags=["behavior"])

_SESSION_SAMPLE_ROWS = 200_000   # safe fallback when session_summary isn't built yet


@router.get("")
def get_behavior(
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
):
    seg_tbl = table("user_segments")

    where_parts = []
    if start_date:
        where_parts.append(f"event_date >= '{start_date}'::DATE")
    if end_date:
        where_parts.append(f"event_date <= '{end_date}'::DATE")
    where_clause = ("WHERE " + " AND ".join(where_parts)) if where_parts else ""

    # ── Session KPIs ──────────────────────────────────────────────────────────
    # Prefer the pre-aggregated single-row session_summary table (generated by
    # the pipeline).  If it doesn't exist yet, fall back to a DuckDB reservoir
    # sample of session_metrics (reads only ~20 MB instead of the full 1.3 GB).
    if os.path.exists(get_table_path("session_summary")):
        # Pre-computed path — zero heavy I/O, negligible memory, instant response.
        # Note: session_summary is an all-time aggregate so date filters are ignored here;
        # the values shown are always the full-dataset averages.
        session_stats = query(f"SELECT * FROM {table('session_summary')}")
    else:
        # Fallback: sample session_metrics to stay within the 512 MB memory budget.
        session_tbl = table("session_metrics")
        session_stats = query(f"""
            SELECT
                ROUND(AVG(view_count), 2)              AS avg_views_per_session,
                ROUND(AVG(unique_products), 2)          AS avg_products_per_session,
                ROUND(AVG(session_duration_minutes), 2) AS avg_session_duration_min,
                ROUND(AVG(total_events), 2)             AS avg_events_per_session,
                ROUND(
                    100.0 * SUM(CASE WHEN converted THEN 1 ELSE 0 END)
                    / NULLIF(COUNT(*), 0), 3
                ) AS session_conversion_rate,
                COUNT(*) AS total_sessions
            FROM {session_tbl}
            USING SAMPLE {_SESSION_SAMPLE_ROWS} ROWS
            {where_clause}
        """)

    # Sessions per user distribution (bucketed).
    # Uses the pre-aggregated user_segments table (1 row/user, total_sessions already computed)
    # instead of re-scanning the raw session_metrics table (millions of rows).
    sessions_distribution = query(f"""
        SELECT
            sessions_bucket,
            COUNT(*) AS user_count
        FROM (
            SELECT
                user_id,
                total_sessions,
                CASE
                    WHEN total_sessions = 1 THEN '1'
                    WHEN total_sessions = 2 THEN '2'
                    WHEN total_sessions BETWEEN 3 AND 5 THEN '3-5'
                    WHEN total_sessions BETWEEN 6 AND 10 THEN '6-10'
                    ELSE '10+'
                END AS sessions_bucket
            FROM {seg_tbl}
        )
        GROUP BY sessions_bucket
        ORDER BY MIN(total_sessions)
    """)

    # Hourly activity heatmap
    hourly_tbl = table("hourly_patterns")
    hourly = query(f"""
        SELECT
            day_of_week,
            hour_of_day,
            views,
            purchases,
            ROUND(revenue, 2) AS revenue
        FROM {hourly_tbl}
        ORDER BY day_of_week, hour_of_day
    """)

    # User segment distribution
    segment_dist = query(f"""
        SELECT
            segment,
            COUNT(*) AS user_count,
            ROUND(AVG(total_spend), 2) AS avg_spend,
            ROUND(AVG(total_sessions), 2) AS avg_sessions
        FROM {seg_tbl}
        GROUP BY segment
        ORDER BY user_count DESC
    """)

    return {
        "session_stats": session_stats[0] if session_stats else {},
        "sessions_distribution": sessions_distribution,
        "hourly_patterns": hourly,
        "user_segments": segment_dist,
    }
